tap "homebrew/bundle"
tap "homebrew/services"
tap "minacle/chntpw"
tap "sidneys/homebrew"
brew "aria2"
brew "bat"
brew "cabextract"
brew "cdrtools"
brew "deno"
brew "lsd"
brew "mysql", restart_service: true
brew "neovim"
brew "tmux"
brew "tree"
brew "wimlib"
brew "minacle/chntpw/chntpw"
