ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.zlogin /Users/shun_harutaro/.zprezto/runcoms/zlogin
ln -sf ~/dotfiles/.zlogout /Users/shun_harutaro/.zprezto/runcoms/zlogout
ln -sf ~/dotfiles/.zpreztorc /Users/shun_harutaro/.zprezto/runcoms/zpreztorc
ln -sf ~/dotfiles/.zprofile /Users/shun_harutaro/.zprezto/runcoms/zprofile
ln -sf ~/dotfiles/.zshenv /Users/shun_harutaro/.zprezto/runcoms/zshenv
ln -sf ~/dotfiles/.zshrc /Users/shun_harutaro/.zprezto/runcoms/zshrc
ln -sf ~/dotfiles/.init.vim /Users/shun_harutaro/.config/nvim/init.vim
